### ISSUE TITLE
add built in plugin system to vitamin

### ISSUE THREAD

**Issue by alepee** [Evaneos/vitaminjs#205]
Vitamin does not allow a project to infer with the build sequence, this cause a few limitations. A way to lever off those limitations and keep build system predictable enough (and vitamin lightweight) would be to allow a few more operations by a plugin API.
An API to alter [webpack `common` build config](https://github.com/Evaneos/vitaminjs/blob/master/config/build/webpack.config.common.js) ?

few plugin ideas (based on my needs):
- postcss-cssnext support
- environment based config (e.g.: https://github.com/railsconfig/config) made easy
- [yaml loader](https://www.npmjs.com/package/yml-loader)

questions are:
1. **for what kind of needs** would you use something like this?
2. **what scope** do we let to this kind of system (API)?
3. let's try it! 🚀

**Comment by johangirod** [comment]
Well, I'm gonna go against the flow here, but I'm not sure vitaminjs **needs** a plugin system. Of course it could be a nice addition. Besides, which build frameworks doesn't come with the possibility to extends it ? Webpack, react-create-app, next... They all do it.

But I'm not sure that something we should do in vitaminjs. To understand why, I should explain what are the design principles of vitaminjs, according to me. 
 
For me, the founding promise of vitaminJS is to **remove all the tooling and framework configuration** overhead that comes with starting a new project, so that the developer can **focus exclusively on the design decisions** of its application.

In order to achieve that, vitaminJS should be **opinonated but non-binding**

### Opinionated
We take decisions. We take them based on what seems to be the community consensus, or what we believe will come to be the next community consensus. We chose react, webpack and redux. We chose css-modules. The aim is to take the maximum of decision, so that the developper don't have to take them.

### Non-binding
I should not feel constrained by using vitaminJS. I should be able to use less, sass. I should be able to use yaml and json to store config. When there is no community consensus, we should not choose a solution over another. So we should provide implementation for both.

Those two principle might seem contradictory. But I'm sure that we can walk the thin line between them and that it is something that can bring tremendous value. 

---

So what does it means in our case ?

It means that I'm favorable to built-in support of postcss-cssnext and yaml loader. 
And for the environment-based config, we can discuss it in more length, but I'm pretty sure it's already possible thanks to the ability to extends `.vitaminrc`

Anyway, this is a proposition, I'm curious to have everybody's feedback on it.

**Comment by alepee** [comment]
css support: https://github.com/Evaneos/vitaminjs/pull/230
yaml support: https://github.com/Evaneos/vitaminjs/pull/231
